#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#yabai -m config debug_output on

# global settings
# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
# yabai -m config window_placement             second_child
# yabai -m config window_topmost               off
# yabai -m config window_shadow                off
# yabai -m config window_opacity               off
# yabai -m config window_opacity_duration      0.0
# yabai -m config active_window_opacity        1.0
# yabai -m config normal_window_opacity        1.0
# yabai -m config window_border                off
# yabai -m config window_border_width          6
# yabai -m config active_window_border_color   0xEEffb374
# yabai -m config normal_window_border_color   0xff555555
# yabai -m config insert_feedback_color        0xffd75f5f
# yabai -m config split_ratio                  0.50
# yabai -m config auto_balance                 off
# yabai -m config mouse_modifier               fn
# yabai -m config mouse_action1                resize
# yabai -m config mouse_action2                move
# yabai -m config mouse_drop_action            swap
# yabai -m config external_bar                 all:30:00

# # general space settings
# yabai -m config layout                       bsp
# yabai -m config top_padding                  50
# yabai -m config bottom_padding               50
# yabai -m config left_padding                 80
# yabai -m config right_padding                80
# yabai -m config window_gap                   20

yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off            \
    window_shadow                off            \
    window_animation_duration    0.0            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    active_window_border_color   0xff775759     \
    normal_window_border_color   0xff555555     \
    window_border_width          4              \
    window_border_radius         12             \
    window_border_blur           off            \
    window_border_hidpi          on             \
    window_border                off            \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  50             \
    bottom_padding               50             \
    left_padding                 80             \
    right_padding                80             \
    window_gap                   20             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                resize         \
    mouse_action2                move           \
    mouse_drop_action            swap

# unmanaged
yabai -m rule --add app="^(Spotify|IINA)$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="SpeedReader" title="Reading" manage=off
yabai -m rule --add title="^.+noVNC$" manage=off
yabai -m rule --add app="scrcpy" manage=off # scrpy for android devices
yabai -m rule --add title="^(Web Inspector|Developer Tools).*" manage=off
yabai -m rule --add app="^(LuLu|Calculator|Voice Memos|Clean Me|SelfControl|Another Day|Oo{4}|Simulator|TomatoBar|1Password)$" manage=off
yabai -m rule --add app="^Tunnelblick$" manage=off
yabai -m rule --add app="^Music$" title="MiniPlayer" manage=off

# setup spaces
yabai -m space 1 --label code
yabai -m space 2 --label browser
yabai -m space 3 --label social
yabai -m space 4 --label uptodate

yabai -m space 5 --label anarchy
yabai -m config --space 5 layout float

yabai -m rule --add app="^(Discord|Microsoft Teams)$" space=social manage=off
yabai -m rule --add app="^Firefox$" space=browser
yabai -m rule --add app="^(Thunderbird|NetNewsWire)$" space=uptodate

echo "yabai configuration loaded.."
